CPSC319-2022/AmazonianPrime

backend/functions/db-init/app.js

[Backend] Update Orders Table in DB

---

frontend/src/components/manage-profile/ManageProfile.tsx

fix: button

---

frontend/src/components/toolbar/AccountButton.tsx
frontend/src/components/toolbar/ToolBar.tsx
frontend/src/redux/reducers/userSlice.ts
frontend/src/utils/useAdminPrivelege.ts

feat: add admin button

---

backend/functions/admin-delete-user/app.js
backend/functions/admin-delete-user/package.json
backend/functions/admin-get-orders/app.js
backend/functions/admin-get-orders/package.json
backend/functions/admin-get-users/app.js
backend/functions/admin-get-users/package.json
backend/functions/admin-modify-user-privilege/app.js
backend/functions/admin-modify-user-privilege/package.json
backend/template.yaml

Contains 4 endpoints for the admin module:
GET admin/users?offset=x&limit=y
GET admin/orders?offset=x&limit=y
DELETE admin/users/:UserID
PUT admin/users/privilege/:UserID
Each require the Admin's UserID to be present within the request body. Privilege requires the desired IsAdmin field passed in the request body as well.

[Backend] Admin Module Endpoints

---

backend/functions/admin-get-users/app.js
backend/template.yaml

added opt name query param for admin search users

---

backend/functions/add-to-cart/app.js

Creating a new shopping cart item:
{
"ListingID": "2",
"Quantity": "1",
}
Updating an existing shopping cart item quantity
{
"ListingID": "2",
"Quantity": "2",
"ShoppingCartItemID": "3"
}

[Backend] Update shopping cart for creating and updating shopping cart items

---

backend/functions/admin-get-users/app.js

feat(admin-get-users): added total user count to return body

---

backend/functions/get-cart/app.js

```
{
"TotalQuantity": 4,
"Subtotal": 12.56,
"PSTTax": 0.88,
"GSTTax" 0.63,
"TotalCost": 14.07,
"Items": [
{
"ShoppingCartItemID": 5,
"UserID": 5,
"ListingID": 2,
"Quantity": 3,
"Listing": {
"ListingID": 2,
"UserID": 1,
"ListingName": "Testing",
"Description": "Describe",
"Cost": 12.56,
"Quantity": 3,
"Category": "Sample",
"Size": "M",
"Brand": "Adidas",
"Colour": "White",
"ItemCondition": "New",
"PostedTimestamp": "2023-03-24T23:40:58.000Z",
"IsActiveListing": 1,
"ImageListingID": 2,
"IsAdmin": 1,
"User": {
"FirstName": "Josh",
"LastName": "Luong",
"Email": "joshopolis321@gmail.com",
"Department": "Development"
},
"ImagePreview": "https://sam-app-imagebucket-34w7kvgi6jez.s3.us-west-2.amazonaws.com/612653d0-f492-464b-9ba4-ca745284e26a.jpeg"
}
}
]
}
```
* ISSUE: …

[Backend] tax calculation on new items in shopping cart

---

frontend/package.json
frontend/src/App.tsx
frontend/src/Paths.ts
frontend/src/components/admin/User.scss
frontend/src/components/admin/User.tsx
frontend/src/components/admin/UsersGrid.scss
frontend/src/components/admin/UsersGrid.tsx
frontend/src/components/admin/UsersPage.scss
frontend/src/components/admin/UsersPage.tsx
frontend/src/components/common/Breadcrumbs.tsx
frontend/src/components/toolbar/AccountButton.tsx
frontend/src/components/toolbar/ToolBar.tsx
frontend/src/redux/api/admin.ts
frontend/src/redux/reducers/adminSlice.ts
frontend/src/redux/reducers/userSlice.ts
frontend/src/redux/store/index.ts
frontend/src/types/paginatedUsers.ts
frontend/yarn.lock

| Nothing      | ![Screenshot 2023-03-28 at 3 55 47 AM](https://user-images.githubusercontent.com/124236661/228214625-88fb991b-c487-4a31-8e16-607c74fdb65b.png)      |
| Nothing      | ![Screenshot 2023-03-28 at 3 55 31 AM](https://user-images.githubusercontent.com/124236661/228214710-3ce8f77b-d956-4406-ab04-1b4f3a9a47b1.png)      |
-Removed temp fix to grant all users admin
-Created UI for users page
-Navigation bar now replaces "Sell" with "Users" when in admin mode
-Created redux reducers for admin APIs
-Hooked up admin APIs (except orders) to frontend (get users, change privilege levels, delete user)
-Added confirmation dialogue for delete …

Admin module users page

---

backend/functions/delete-listing-id/app.js

Same endpoint, we now delete from a shopping cart

[Backend] Delete a listing -> delete from all shopping carts

---

backend/functions/admin-get-users/app.js
frontend/package.json
frontend/src/App.tsx
frontend/src/Paths.ts
frontend/src/components/admin/User.scss
frontend/src/components/admin/User.tsx
frontend/src/components/admin/UsersGrid.scss
frontend/src/components/admin/UsersGrid.tsx
frontend/src/components/admin/UsersPage.scss
frontend/src/components/admin/UsersPage.tsx
frontend/src/components/common/Breadcrumbs.tsx
frontend/src/components/toolbar/AccountButton.tsx
frontend/src/components/toolbar/ToolBar.tsx
frontend/src/redux/api/admin.ts
frontend/src/redux/reducers/adminSlice.ts
frontend/src/redux/reducers/userSlice.ts
frontend/src/redux/store/index.ts
frontend/src/types/paginatedUsers.ts
frontend/yarn.lock

Admin get users now should return total searched users instead of just all users

Fix total users

---

backend/functions/append-sns-token/app.js
backend/functions/append-sns-token/package.json
backend/functions/check-payment/app.js
backend/functions/check-payment/package.json
backend/functions/checkout/app.js
backend/functions/checkout/package.json
backend/functions/db-init/app.js
backend/functions/retry-payment/app.js
backend/functions/retry-payment/package.json
backend/functions/send-token/app.js
backend/functions/send-token/package.json
backend/functions/sf-get-cart/app.js
backend/functions/sf-sns-send-token/app.js
backend/functions/sf-sns-send-token/package.json
backend/functions/sf-sns-wait-token/app.js
backend/functions/sf-sns-wait-token/package.json
backend/functions/sf-throw-sqs-error/app.js
backend/functions/sf-throw-sqs-error/package.json
backend/statemachine/order_workflow.asl.json
backend/template.yaml

[Backend] Adding SNS and SQS in Checkout Flow (DRAFT)

---

backend/functions/get-cart/app.js

fix quantity in total calculation

---

backend/functions/add-address/app.js
backend/functions/add-banking/app.js
backend/functions/add-payment/app.js
backend/functions/add-shipping/app.js
backend/functions/add-to-cart/app.js
backend/functions/admin-delete-user/app.js
backend/functions/admin-get-orders/app.js
backend/functions/admin-get-users/app.js
backend/functions/admin-modify-user-privilege/app.js
backend/functions/admin-update-user/app.js
backend/functions/check-payment/app.js
backend/functions/clear-cart/app.js
backend/functions/create-listing/app.js
backend/functions/db-query-table/app.js
backend/functions/delete-listing-id/app.js
backend/functions/get-banking/app.js
backend/functions/get-cart/app.js
backend/functions/get-listing-id/app.js
backend/functions/get-listings/app.js
backend/functions/get-payment/app.js
backend/functions/get-shipping/app.js
backend/functions/get-user/app.js
backend/functions/remove-from-cart/app.js
backend/functions/sf-create-order/app.js
backend/functions/sf-get-cart/app.js
backend/functions/update-banking/app.js
backend/functions/update-listing/app.js
backend/functions/update-user/app.js
backend/helpers/nodejs/node_modules/dbConnection.js
backend/template.yaml

[Backend] DIsconnect DB Connections

---

frontend/package.json
frontend/src/App.tsx
frontend/src/components/cart/CartPage.scss
frontend/src/components/cart/CartPage.tsx
frontend/src/components/common/Timer.tsx
frontend/src/redux/api/shoppingCart.ts
frontend/src/redux/reducers/appSlice.ts
frontend/src/types/payment.ts
frontend/src/types/shoppingCartItems.ts
frontend/yarn.lock

Connect checkout

---

frontend/src/components/admin/UsersPage.tsx

Fix pagination for admin module users page

fix(UsersPage): pagination

---

backend/functions/email-confirmation/app.js
backend/functions/email-confirmation/package.json
backend/template.yaml

Send conformation email end point 
```
{
"email":"mahmoudalkhatib.ubc@gmail.com"
}
```

Tested and working send email confirmation

---

backend/functions/get-user-details/app.js
backend/functions/get-user-details/package.json
backend/functions/send-delivered/app.js
backend/functions/send-delivered/package.json
backend/functions/send-order/app.js
backend/functions/send-order/package.json
backend/functions/send-shipped/app.js
backend/functions/send-shipped/package.json
backend/functions/update-delivered/app.js
backend/functions/update-delivered/package.json
backend/functions/update-shipped/app.js
backend/functions/update-shipped/package.json
backend/statemachine/email_workflow.asl.json
backend/statemachine/order_workflow.asl.json
backend/template.yaml

Tested running a local instance against aws. Adds a call to Checkout workflow that sends 3 emails, order confirmation, order shipped and order delivered with 30 second timeouts between each (will extend in next pr)

[Backend] Email step function

---

backend/template.yaml

revert policy changes

---

backend/statemachine/order_workflow.asl.json

revert integration of email

---

backend/functions/get-user-details/app.js
backend/functions/get-user-details/package.json
backend/functions/send-delivered/app.js
backend/functions/send-delivered/package.json
backend/functions/send-order/app.js
backend/functions/send-order/package.json
backend/functions/send-shipped/app.js
backend/functions/send-shipped/package.json
backend/functions/update-delivered/app.js
backend/functions/update-delivered/package.json
backend/functions/update-shipped/app.js
backend/functions/update-shipped/package.json
backend/statemachine/email_workflow.asl.json
backend/statemachine/order_workflow.asl.json
backend/template.yaml

ok lets go

---

backend/functions/append-sns-token/app.js
backend/functions/check-payment/app.js
backend/functions/check-quantity/app.js
backend/functions/payment-fail/app.js
backend/functions/payment-sim/app.js
backend/functions/reserve-listings/app.js
backend/functions/reserve-listings/package.json
backend/functions/retry-payment/app.js
backend/functions/sf-error-handler/app.js
backend/helpers/nodejs/node_modules/errorStates.js
backend/statemachine/order_workflow.asl.json
backend/template.yaml

- Fixed issue where the cc used for retry is still invalid. Will now throw an Expired Credit Card error
- Handled case where retry is not attempted after 5 minutes. Will throw an Expired Credit Card error as well
- Reduced item inventory and unreserved if there is an error in checkout process
- Changed cc date checks to match FE logic
* ISSUE: [31](https://github.com/CPSC319-2022/AmazonianPrime/issues/31)

[Backend] Step function V3

---

backend/functions/sf-create-order/app.js
backend/functions/sf-error-handler/app.js
backend/functions/sf-get-cart/app.js
backend/statemachine/order_workflow.asl.json

feat: add taxes to order

---

backend/functions/admin-get-orders/app.js

Add more information to get orders

---

backend/functions/get-blocked-users/app.js
backend/functions/get-blocked-users/package.json
backend/functions/get-user/app.js
backend/functions/payment-sim/app.js
backend/helpers/nodejs/node_modules/errorStates.js
backend/template.yaml

[Backend] Disallow Blocked Users

---

backend/functions/admin-get-orders/app.js
backend/functions/get-listings/app.js

[Backend] Add order by clause
